### ISSUE TITLE
[doc] Set up documentation page

### ISSUE THREAD

**Issue by bingogome** [bingogome/samm#15]

**Comment by MedAIerHHL** [comment]
Can you give me a SAMM plug-in package directly to simplify installation in 3DSlicer? Or can you give a demo? Thanks！（I want to recommend it to my doctor friends who usually  use 3D Slicer to segment MRIs.）

**Comment by bingogome** [comment]
This is a related request in #10 . Need some more time to figure out the axis issue in #13 first.
