### ISSUE TITLE
[dev] BUG of 2D image in slicer. add 2d imgae support

### ISSUE THREAD

**Issue by lancesye** [bingogome/samm#16]
I want to use Samm to label a 2D  image in 3D slicer. But Samm have not support 2d image yet. In samm-workspace, it generate too much slices. However, 2D image should only have one slice. I think I should modify the SammBaseLib\LogicSamm.py.  What should I do? 
![图片1](https://user-images.githubusercontent.com/25152572/231801325-db126613-5eb4-470d-8e37-00b95fcbf93a.png)
![图片2](https://user-images.githubusercontent.com/25152572/231801408-544c20ad-665e-4db2-9481-4d4d949f7536.png)

**Comment by lancesye** [comment]
[OCTA.zip](https://github.com/bingogome/samm/files/11228149/OCTA.zip)

**Comment by lancesye** [comment]
Thank you very much for your contribution

**Comment by lancesye** [comment]
I notice that you use Markups as SAM model label points. But the coordinate of marking a point in 2D image have something wrong. When I release the left button of the mouse, the marked point move to (0,0,0) . It seems a problem with the slicer itself, and maybe I need to recompile the slicer, but this step is very complex. I don't have a good solution.
![image](https://user-images.githubusercontent.com/25152572/231979709-27c7fa6d-254c-426d-bcb3-2149da8efb1e.png)
![image](https://user-images.githubusercontent.com/25152572/231981173-b1b2a9c7-d976-4a30-83ce-d63134c20357.png)

**Comment by bingogome** [comment]
Looks like after resolving #13, 2D image like the one you sent can also be used. I tried it out and it worked. Only problem is the fiducial points sync is slightly off and will disappear. I am pushing a new commit which should take care of that.

**Comment by bingogome** [comment]
c41750f81672335aea7d5242417f18b67a8ff157 

Closing issue. Reopen if the problem persists.
