### ISSUE TITLE
ValueError: mmap length is greater than file size。

### ISSUE THREAD

**Issue by woailunhua** [bingogome/samm#26]
Sorry to bother you, but I'm running into a problem.I'm running in a Linux environment.
 I ran the sam_server.py file first, and I clicked Compute embedding in slicer's Samm Base and waited for the sam_server.py to run successfully and output all images have been processed. Then I clicked on Start Mask Sync inside Prompts and the red dot below. Error reported in slicer terminal:"Value_Error: mmap length is greater than file size". Is there any way you can deal with this?  Looking forward to your help.

**Comment by bingogome** [comment]
> Sorry to bother you, but I'm running into a problem.I'm running in a Linux environment.
> 
>  I ran the sam_server.py file first, and I clicked Compute embedding in slicer's Samm Base and waited for the sam_server.py to run successfully and output all images have been processed. Then I clicked on Start Mask Sync inside Prompts and the red dot below. Error reported in slicer terminal:"Value_Error: mmap length is greater than file size". Is there any way you can deal with this?  Looking forward to your help.

Thanks for trying it out. Can the test data be shared?

**Comment by woailunhua** [comment]
[](url)

- [ ]
