### ISSUE TITLE
 [dev] M1 support 

### ISSUE THREAD

**Issue by drahmedshaheen** [bingogome/samm#27]
I have installed the extension and the right dependencies but it is not working
It freezes after computing the parameters, I hope you can provide m1 support soon.
best regards

**Comment by bingogome** [comment]
> I have installed the extension and the right dependencies but it is not working
> 
> It freezes after computing the parameters, I hope you can provide m1 support soon.
> 
> best regards 

Thanks for the bug report. Can you provide your GPU information? In addition, is there an error printout from sam_server.py terminal?

**Comment by drahmedshaheen** [comment]
I use mac with M1 chip

This plugin dir: /Applications/Slicer.app/Contents/Extensions-31382/NvidiaAIAssistedAnnotation/lib/Slicer-5.2/qt-scripted-modules

**Comment by drahmedshaheen** [comment]
I use mac with M1 chip, and it is just freezes and at the end the system says the app is not responding

**Comment by bingogome** [comment]
I realized M1 meaning a newer Mac device. I'm flagging this issue as a development item. 

As of now, SAM network needs to run in Cuda, which is not in Mac anymore. There might be ways to work around it but I'll need to investigate more.

**Comment by drahmedshaheen** [comment]
Actually, I installed SAM and it worked well on conda env, it is not working with the GPU "mps", but it is still working with the CUP so if you could add this option for now, it may solve the bug

**Comment by drahmedshaheen** [comment]
https://github.com/facebookresearch/segment-anything/pull/122

**Comment by bingogome** [comment]
> Actually, I installed SAM and it worked well on conda env, it is not working with the GPU "mps", but it is still working with the CUP so if you could add this option for now, it may solve the bug 

That's good to know. It was a very long time ago that I do deep learning on Mac. In that case this should be a easy fix.

**Comment by drahmedshaheen** [comment]
Thank you so much
Looking forward to citing your amazing paper and tool in our research

**Comment by drahmedshaheen** [comment]
> > Actually, I installed SAM and it worked well on conda env, it is not working with the GPU "mps", but it is still working with the CUP so if you could add this option for now, it may solve the bug
> 
> That's good to know. It was very long time ago that I do deep learning on Mac. In that case this should be a easy fix.
> 
> I was not aware PyTorch has an "mps" device option.

M1 and M2 chips are very strong in deep learning, however, there is still a lot of bugs and PyTorch are doing a great job
