### ISSUE TITLE
Slicer crashes upon clicking start mask sync

### ISSUE THREAD

**Issue by BenyAlbatross** [bingogome/samm#33]
My input is a nifti file. After clicking compute embedding, the terminal outputs "All images have been processed", indicating that embedding has been successfully computed. I can see that the .pkl files have been produced. When I click on the prompts tab and click on start mask sync, slicer closes. There is no error message in the terminal. Slicer only crashes when start mask sync is clicked after embeddings have been computed.

**Comment by bingogome** [comment]
Could you please share the environment information?

**Comment by vankhoa21991** [comment]
Hello, I have the same issue, I'm using ubuntu 20.4, with slicer 5.2.2. It crashes when I turn on sync mask.

**Comment by BenyAlbatross** [comment]
Hi, apologies for the late reply. I'm using Ubuntu 22.04 with slicer 5.2.2

**Comment by bingogome** [comment]
This issue should be fixed now in https://github.com/bingogome/samm/commit/5b63c7dfa120c39066215fb766f8b246be3e2414 by switching communication from memory mapping to ZMQ.
