### ISSUE TITLE
OSError: [Errno 22] Invalid argument: 'C:\\Users\\38561\\samm\\samm-python-terminal\\samm-workspace\\mask.memmap'

### ISSUE THREAD

**Issue by xiaoli26** [bingogome/samm#34]
All images have been processed.
ERROR:root:Traceback (most recent call last):
  File "C:\Users\38561\samm\samm-python-terminal\sam_server.py", line 272, in main
    srv.infer_image( \
  File "C:\Users\38561\samm\samm-python-terminal\sam_server.py", line 188, in infer_image
    memmap = np.memmap(os.path.join(self.workspace, "mask.memmap"), dtype='bool', mode='w+', shape=self.masks[0].shape)
  File "C:\Users\38561\AppData\Roaming\Python\Python39\site-packages\numpy\core\memmap.py", line 228, in __new__
    f_ctx = open(os_fspath(filename), ('r' if mode == 'c' else mode)+'b')
OSError: [Errno 22] Invalid argument: 'C:\\Users\\38561\\samm\\samm-python-terminal\\samm-workspace\\mask.memmap'

Everthing went well except the error message.

**Comment by bingogome** [comment]
The error looks like something file lock related. The data transmission will need to be optimized using #10 . Currently, it will still work even with the error. I am going to write an ignore condition.

**Comment by xiaoli26** [comment]
> 

Thanks for your reply and your excellent work!
