### ISSUE TITLE
[bug] incorrect segmentation slice alignment

### ISSUE THREAD

**Issue by lcukyfuture** [bingogome/samm#36]
When I finish embedding, there are 188 slices in the CT image, but only the first 94 slices can be added the prompt, the later slices fail to be added, and the following error is reported.

ERROR:root:Traceback (most recent call last):
  File "./samm-python-terminal/sam_server.py", line 272, in main
    srv.infer_image( \
  File "./samm-python-terminal/sam_server.py", line 188, in infer_image
    memmap = np.memmap(os.path.join(self.workspace, "mask.memmap"), dtype='bool', mode='w+', shape=self.masks[0].shape)
  File "C:\Users\admin\anaconda3\envs\samm\lib\site-packages\numpy\core\memmap.py", line 228, in __new__
    f_ctx = open(os_fspath(filename), ('r' if mode == 'c' else mode)+'b')
OSError: [Errno 22] Invalid argument: 'C:\\3Dslicer\\samm\\samm-python-terminal\\samm-workspace\\mask.memmap'

**Comment by bingogome** [comment]
The error itself should be a lock issue (#34). 

The half of the image could not show is somewhat reproducible in the MRI sample from Slicer. This is something related to the RASToIJK problem. In most cases when it happens, if you see carefully at the other views, you could notice there are slices of segmentation generated, but not aligned correctly on the RED view (the working view). I think it's a rounding problem.

**Comment by bingogome** [comment]
This problem should have been improved by the recent change of the architecture.
