### ISSUE TITLE
Not able to git clone the git@github.com:bingogome/samm.git repo

### ISSUE THREAD

**Issue by shenw000** [bingogome/samm#43]
I attempted to gt clone the git@github.com:bingogome/samm.git repo by the following command:
git clone git@github.com:bingogome/samm.git

and received following error:
==========================================================================
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Any idea how to fix it?

Thanks!

**Comment by bingogome** [comment]
This looks like more of a git configuration issue. Please refer to Github's documentations on authentication.
