### ISSUE TITLE
When I segment a 3D Volume, how could I mask different frames of image in one initialization

### ISSUE THREAD

**Issue by WHU-YH-jx** [bingogome/samm#48]

**Comment by WHU-YH-jx** [comment]
Now I segment one frame of the 3D image, I must re-initialization then put prompt points in next frame. Is it possible to mask all frames of the 3D image in one initialization.

**Comment by bingogome** [comment]
The initialization should be a one-time thing. Once initialized, all embeddings throughout the volume are cached. The new changes https://github.com/bingogome/samm/commit/5b63c7dfa120c39066215fb766f8b246be3e2414 made some improvements over system glitches and should be easier to use.
