### ISSUE TITLE
Questions about segmenting and labeling different cells in one image 

### ISSUE THREAD

**Issue by BurtonQin** [bingogome/samm#49]
Thanks for your excellent work!
I have some questions about segmenting and labeling different cells in one image:

1. How to create different labels for different cells in one image. Suppose there are two types of cells A and B, I want to segment A cells and label them with A, and then segment B cells and label them with B. But I did not find such operations in demo video.
2. How to reuse the result of "compute embedding"? I want to compute once and reuse it every time I re-opened 3DSlicer.
3. 3DSlicer occasionally crashes when running samm. For example, it crashes when I press "start mask sync" before adding prompts or when I create a new segment.

**Comment by bingogome** [comment]
1. You could create different segmentations in the Segmentation module, then in SAMM, specify which segmentation you are assigning. 
2. It was possible to do it before, but in the recent change, I removed savings for stability reasons. I am adding an issue to bring it back with a better solution: #57 
3. This should be improved with the most recent changes.
