### ISSUE TITLE
No module named 'mobile'sam'

### ISSUE THREAD

**Issue by bayers92** [bingogome/samm#66]
All parts of installation are working for me until trying to start the sam_server I'm getting the error message:
"from mobile_sam import sam_model_registry as sam_model_registry_mobile
ModuleNotFoundError: No module named 'mobile_sam'"

**Comment by DaiDuncan** [comment]
> All parts of installation are working for me until trying to start the sam_server I'm getting the error message: "from mobile_sam import sam_model_registry as sam_model_registry_mobile ModuleNotFoundError: No module named 'mobile_sam'"

pls check here to install the mobile_sam dependency.
