### ISSUE TITLE
[MedSAM support for semi-automated segment]how to use MedSAM model with the updated 3D-Slicer extention?

### ISSUE THREAD

**Issue by DaiDuncan** [bingogome/samm#67]
### Env
- Ubuntu 20.04 LTS
- 3D Slicer 5.2.2
- Python 3.9.13

### Current state

- [ x ] 1 Samm model with 3D-Slicer extension (Samm Base) based on release v1.0.3 on May 5 works fine.
- [ x ] 2 The updated MedSAM model in Aug works fine with the python file (see figure below) 
![image](https://github.com/bingogome/samm/assets/14899140/8fd631cd-6688-4091-a9fb-fd3e3a254ce5)

- [ ] 3 However, the updated 3D-Slicer extension has no function of semi-automated segmentation, is that right? (see figure below: extension in the left part is Samm Base, in the right part is the updated extension in Aug.)
![image](https://github.com/bingogome/samm/assets/14899140/6bde6acb-36cd-4680-bc7f-39ab8a23def7)

**Comment by bingogome** [comment]
Hi

Thanks for using the extension. It seems that the right side of the image is an example extension from Slicer. It is the extension created if you create a new scripted extension. It does different things.

**Comment by DaiDuncan** [comment]
> Hi
> 
> Thanks for using the extension. It seems that the right side of the image is an example extension from Slicer. It is the extension created if you create a new scripted extension. It does different things.

Thank you a lot for the hint. Now it works again with MedSAM model!
