### ISSUE TITLE
Using SAMM to train automatic segmentation

### ISSUE THREAD

**Issue by VSPuzzler** [bingogome/samm#68]
Hello, I was trying to use SAMM to train a model for automatic artery segmentation. I have collected the data needed for this. Is it possible to do this on the 3D slicer extension?

**Comment by bingogome** [comment]
Hi thanks for using the extension. It doesn't support auto-segmentation yet. It's a pending feature. You could use other packages like MedSam. It is also open sourced.

**Comment by VSPuzzler** [comment]
> Hi thanks for using the extension. It doesn't support auto-segmentation yet. It's a pending feature. You could use other packages like MedSam. It is also open sourced.

Could I use SAMM to train for semi-automatic segmentation? Also would it be possible to train a model with SAMM outside of 3D slicer? Thank you for the help.

**Comment by bingogome** [comment]
You should be able to. The community has been publishing some pretty interesting SAM variants models with the emphasis on medical images. MedSam as I recommended earlier is one of them. It allows you to fine tune. I'm sure the others would have the same/similar.

**Comment by VSPuzzler** [comment]
Is MedSam on 3d slicer?
