### ISSUE TITLE
Module crashes after embedding is computed

### ISSUE THREAD

**Issue by dzenanz** [bingogome/samm#8]
```log
Traceback (most recent call last):
  File "M:\Ethicon\samm\samm\SammBase\SammBaseLib\WidgetSammBase.py", line 103, in onPushComputePredictor
    self.logic.processComputePredictor()
  File "M:\Ethicon\samm\samm\SammBase\SammBaseLib\LogicSamm.py", line 113, in processComputePredictor
    f = open(self.ui.pathWorkSpace.currentPath.strip(), "w")
PermissionError: [Errno 13] Permission denied: 'C:/Temp/User/Slicer/Workspace/'
```
This happens with 8d2a23b396a12f10fec47e54b26752c4ea99b57f and Slicer 5.3.0-2023-03-22 r31691 / fbc2ede

**Comment by bingogome** [comment]
What path did you use for the "Work Space"? Was it a folder by any chance? I meant it to be a "config.yaml" file. I updated the UI string, but will code something that automatically generate a workspace.

**Comment by dzenanz** [comment]
Yes, I used a folder.

**Comment by bingogome** [comment]
Hi, thanks for trying it out. The readme was just updated (2 minutes ago). On my test environment, the TLDR instruction worked well. The hardcoded path are eliminated. Please let me know if there is still issues running it. Your patience is much appreciated!

**Comment by dzenanz** [comment]
Instructions are now clearer, and it is more user friendly.
